"""
Torsten Timm's Self-Citation Model Generator.
Simulates a scribe copying and modifying recent words, explaining the paradox of
long-range thematic memory alongside collapsed 2nd-order conditional entropy and curious repetitions.
"""

import random
from typing import List, Optional


class TimmSelfCitationGenerator:
    """
    Implements Torsten Timm's self-citation hypothesis:
    Words are generated by selecting a recently written word from a memory buffer
    and applying stochastic scribal mutations (glyph substitution, prefix swapping, suffix alteration).
    """

    DEFAULT_PREFIXES = ["qo", "ch", "sh", "d", "y", "ol", "or", "ot"]
    DEFAULT_ROOTS = ["k", "t", "e", "ee", "ai", "ar", "al", "ey"]
    DEFAULT_SUFFIXES = ["edy", "ain", "ar", "dy", "y", "am", "or", "hy"]

    def __init__(
        self,
        memory_buffer_size: int = 15,
        mutation_rate: float = 0.35,
        immediate_repeat_rate: float = 0.08,
        seed: Optional[int] = 42
    ):
        self.buffer_size = memory_buffer_size
        self.mutation_rate = mutation_rate
        self.immediate_repeat_rate = immediate_repeat_rate
        if seed is not None:
            random.seed(seed)

    def _generate_seed_word(self) -> str:
        """Generates a base morphologically compliant voynichese pseudo-word."""
        prefix = random.choice(self.DEFAULT_PREFIXES) if random.random() > 0.3 else ""
        root = random.choice(self.DEFAULT_ROOTS)
        suffix = random.choice(self.DEFAULT_SUFFIXES) if random.random() > 0.2 else ""
        return f"{prefix}{root}{suffix}" or "qokedy"

    def _mutate_word(self, word: str) -> str:
        """Applies single-step scribal mutation to a cited word."""
        mut_type = random.choice(["prefix", "suffix", "glyph"])
        
        if mut_type == "prefix":
            for p in self.DEFAULT_PREFIXES:
                if word.startswith(p):
                    new_p = random.choice(self.DEFAULT_PREFIXES)
                    return new_p + word[len(p):]
            return random.choice(self.DEFAULT_PREFIXES) + word

        elif mut_type == "suffix":
            for s in self.DEFAULT_SUFFIXES:
                if word.endswith(s):
                    new_s = random.choice(self.DEFAULT_SUFFIXES)
                    return word[:-len(s)] + new_s
            return word + random.choice(self.DEFAULT_SUFFIXES)

        else:
            # Single character substitution
            if len(word) > 2:
                idx = random.randint(0, len(word) - 1)
                replacement = random.choice(["e", "d", "o", "k", "y", "l", "r"])
                return word[:idx] + replacement + word[idx + 1:]
            return self._generate_seed_word()

    def generate(self, num_words: int = 1000) -> List[str]:
        """
        Generates a sequence of Voynich-like words using the self-citation process.
        """
        if num_words <= 0:
            return []

        buffer: List[str] = [self._generate_seed_word() for _ in range(5)]
        generated_words: List[str] = []

        for _ in range(num_words):
            # 1. Immediate repetition check
            if generated_words and random.random() < self.immediate_repeat_rate:
                word = generated_words[-1]
            else:
                # 2. Select from recent memory buffer (exponential recency bias)
                weights = [1.0 / (i + 1) for i in range(len(buffer))]
                total_w = sum(weights)
                probs = [w / total_w for w in weights]
                selected = random.choices(buffer, weights=probs, k=1)[0]

                # 3. Apply mutation or cite directly
                if random.random() < self.mutation_rate:
                    word = self._mutate_word(selected)
                else:
                    word = selected

            generated_words.append(word)
            buffer.insert(0, word)
            if len(buffer) > self.buffer_size:
                buffer.pop()

        return generated_words
